#!/bin/sh

SITE=${1:-1}
FMT=${2:-%02x%02x%02x%02x}
WRITE=${WRITE:-1}
READ=${READ:-1}

[ $WRITE -eq 1 ] && \
for chip in 0 1 2 3; do
        for chan in 0 1 2 3 4 5 6 7; do
                v32=$(printf $FMT $SITE $chip $chan $chan)
                knob=/dev/acq426/$SITE/$chip/in_voltage${chan}_test_pattern32
                echo write $v32 to $knob
                echo $v32 > $knob
        done
done

ecode=0

[ $READ -eq 1 ] && \
for chip in 0 1 2 3; do
        for chan in 0 1 2 3 4 5 6 7; do
                v32=$(printf $FMT $SITE $chip $chan $chan)
                knob=/dev/acq426/$SITE/$chip/in_voltage${chan}_test_pattern32
                val=$(cat $knob)
                if [ "$v32" = "$val" ]; then
                        echo "$knob $val GOOD"
                else
                        echo "$knob $val FAIL"
                        ecode=1
                fi
        done
done

exit $ecode
