#!/bin/sh

# --all is handy for humans, but CHIPS is easier to script ..
CHIPS=${CHIPS:-ABCDEFGH}
VERBOSE=${VERBOSE:-0}
LIVE=${LIVE:-1}

if [ "x$1" == "--all" ]; then
	export args="--all"
elif [ "x$1" != x${1#--chips*} ]; then
	export args="$1"
else
	export args="--chips=$CHIPS"
fi

args="$args -t1"

export SITE=${SITE:-1}

DATA32=$(cat /dev/acq400.${SITE}.knobs/data32)

echo "++ acq465_adc.init SITE:$SITE 01"

reset=${2:-1}
printf "Reset? = %d\n" $reset

#REG02=d0 # Low Power Mode
REG02=d1 # High Perfomance Mode
REG10=02 # Enable Input Ref Gain Correction
REG11=00 # Controls number of bits in data word; set below
REG12=01 # Dual channel mode. D0 and D1
REG24=01 # VCM = AVDD/2 = 2.5 V
REG25=28 # Switch on MCLK_CNT and Overvoltage monitor

acq465_reg() {
	[ $VERBOSE -eq 1 ] && echo /etc/acq400/${SITE}/acq465_reg $args $*
	[ $LIVE -ne 0 ] && /etc/acq400/${SITE}/acq465_reg $args $*
}
acq465_mclkmon() {
	[ $VERBOSE -eq 1 ] && echo /etc/acq400/${SITE}/acq465_mclkmon $args $*
	[ $LIVE -ne 0 ] && /etc/acq400/${SITE}/acq465_mclkmon $args $*
}

acq465_readall() {
	[ $VERBOSE -eq 1 ] && echo /etc/acq400/${SITE}/acq465_readall $args $*
	[ $LIVE -ne 0 ] && /etc/acq400/${SITE}/acq465_readall $args $* > /dev/null
}

acq465_filter_all() {
	[ $VERBOSE -eq 1 ] && echo /etc/acq400/${SITE}/acq465_filter $args $*
	[ $LIVE -ne 0 ] && /etc/acq400/${SITE}/acq465_filter $args $*
}

write_regs(){
	set.site ${SITE} _adc_hax 0x00 # Clear ADC hax reg

	### Disable ODR and DCLK
	set.site ${SITE} _adc_hax 0x22

	### RESET
	#[ $reset -eq 1 ] && set.site ${SITE} _adc_hax 0x08 && sleep 1 && set.site ${SITE} _adc_hax 0x00 # HW reset; belt and braces
	[ $reset -eq 1 ] && set.site ${SITE} adc_reset 1
	sleep 2

	# Read all the registers, this initial read seems to ensure the first writes are successful
	acq465_readall

	### Initial values to registers

	acq465_reg 0x02 0x$REG02 # High Performance Mode
	acq465_reg 0x10 0x$REG10 # Enable Input Ref Gain Correction
	acq465_reg 0x12 0x$REG12 # Dual channel mode. D0 and D1

	acq465_reg 0x24 0x$REG24 # VCM = AVDD/2 = 2.5 V
	acq465_reg 0x25 0x$REG25 # Switch on MCLK_CNT and Overvoltage monitor

	FILTER=0
	if [ -e /etc/acq400/${SITE}/acq465_filter_default ]; then
		FILTER=$(cat /etc/acq400/${SITE}/acq465_filter_default)
	fi
	acq465_filter_all $FILTER
	echo $FILTER > /dev/acq400.${SITE}.knobs/filter_sel

	# Data bitwidth
	#set.site $SITE _adc_hax 0x62   # set FPGA to include status bits in ADC word
	set.site $SITE data32 $DATA32 # BEWARE. Is the act of setting data32 invoking an SPI WR to 0x11 under the hood?
	if [ $DATA32 -eq 1 ]; then
		REG11=20    # no status bits
	#	REG11=30
	else
		REG11=00    # no status bits
	#	REG11=10
	fi
	acq465_reg 0x11 0x$REG11
	logger -t acq465_adc.init acq465_reg 0x11 0x$REG11
}

test_regs() {
	echo -e "    REG $1, look for $2"
	acq465_knobs -t1 acq465_reg $1;echo ""
	test=$(acq465_knobs acq465_reg $1 | grep -o "=00${2}" | wc -l);
}

check_regs() {
	test_regs $1 $2
	if [[ $test = "8" ]];then
		echo -e "PASS!\n"
	else
		echo -e "FAIL! FAIL! FAIL!\n"
		reg_check_fail=1
	fi
}

check_pll() {
	test_regs 0x15 01
	if [[ $test = "8" ]];then
		pll_check_fail=0
	else
		pll_check_fail=1
	fi
}

check_fsettle() {
	test_regs 0x41 0f
	if [[ $test = "8" ]];then
		fsettle_fail=0
	else
		fsettle_fail=1
	fi
}

check_digif() {
	test_regs 0x02 f1
	if [[ $test = "8" ]];then
		digif_check_fail=0
	else
		digif_check_fail=1
	fi
}




### ACTION

logger -t acq465_adc.init 01
caput $(hostname):0:ACQ465:POLL 0

set top_retry=0

while true; do
	reg_check_fail=0
	pll_check_fail=0
	fsettle_fail=0
	digif_check_fail=0
	write_regs

	top_retry=$((top_retry+1))
	if [ $top_retry -gt 10 ]; then
	    break
	fi

	### Check all regs
	acq465_readall
	check_regs 0x02 $REG02
	check_regs 0x10 $REG10
	check_regs 0x11 $REG11
	check_regs 0x12 $REG12
	check_regs 0x24 $REG24
	check_regs 0x25 $REG25

	### Enable ODR; DCLK will automatically enable after the DIG_IF_RESET
	set.site $SITE _adc_hax 0x02

	### Wait for PLL lock
	sleep 1
	set retry=0
	acq465_readall

	while true; do
		retry=$((retry+1))
		if [ $retry -gt 3 ]; then
			break
		fi

		check_pll # PLL Lock
		if [[ $pll_check_fail == 0 ]];then
			echo -e "PLL LOCK - PASS!\n";
			break
		else
			echo -e "PLL LOCK - FAIL! FAIL! FAIL!\n";
			sleep 1
			acq465_readall
		fi
	done

	# Check for filters settled
	while true; do
		retry=$((retry+1))
		if [ $retry -gt 3 ]; then
			break
		fi

		check_fsettle # Filters Settled
		if [[ $fsettle_fail == 0 ]];then
			echo -e "Filters SETTLED - PASS!\n";
			break
		else
			echo -e "Filters SETTLED - FAIL! FAIL! FAIL!\n";
			sleep 1
			acq465_readall
		fi
	done

	if [[ $reg_check_fail == 0 ]] && [[ $pll_check_fail == 0 ]] && [[ $fsettle_fail == 0 ]];then
		echo "Successful setup!"
		break
	else
		echo "ERROR. Re-running ADC setup!"
	fi

done


sleep 1
### Now do a DIG_IF_RESET; Beware, in the FPGA logic, we require ODR to be running and PLLs locked to produce a valid DIG_IF_RESET
acq465_knobs -r $SITE


 ### Lockout SW access to SPI & reset
set.site $SITE _adc_hax 0x15

