#!/bin/sh

ULB=/usr/local/bin
source $ULB/mod_id.sh

if [ "x$1" = "xall" ]; then
	sites=$(set.site 0 aggregator | awk '{print $2}' | grep -o '[1-6]')
	for site in $sites; do
		/usr/local/bin/ao420_init $site > /dev/null
	done
	exit 0
fi


SITE=${1:-0}
MTYPE=${2:-0}
FRU_PART_NUM=${3:-NOFRUPART}
KNOBS=/dev/acq400.${SITE}.knobs
# MODEL re
MODEL=$(cat $KNOBS/module_name)
EK=/etc/acq400/$SITE




case $FRU_PART_NUM in
AO420FMC-4-16-CS3*)
        SET_UNIPOLAR=1;;
*)
        SET_UNIPOLAR=0;;
esac

mkdir -p ${EK}

# experimental: assume all range knobs are 
make_ao422_range_knobs() {
        echo "EARLY make_ao422_range_knobs"
        nc=$(cat $EK/NCHAN)
        [ $nc -eq 5 ] && echo 1 > $KNOBS/ch5_en

        for ch in $(seq ${nc}); do
                knob=$EK/dac_range_$(printf "%02d" $ch)
                rm -f $knob
                cat - >$knob  << EOF
#!/bin/sh
# arg: 1:10V, anything else: 5V
range_code=0x02004d00
[ "x\$1" = "x1" ] && range_code=0x02004e00
set.sys ${KNOBS}/dac_enable 0
set.sys ${KNOBS}/dacreset 1
set.sys ${KNOBS}/dacreset 0
set.sys ${KNOBS}/dacspi 0x037f0000       # Clear Code, offset binary
set.sys ${KNOBS}/dacspi \$range_code
set.sys ${KNOBS}/dac_range_0$ch \${1:-0}
set.sys ${KNOBS}/dac_enable 1
EOF
                chmod 555 $knob
        done
}

vset_sys() {
	echo set.sys $1 $2
	set.sys $1 $2
#	echo get.sys $1 $(get.sys $1)
}

if [ "x$4" = "xEARLY" ]; then
        [ -z $AO422_NO_RANGE_DACSPI ] && make_ao422_range_knobs
        exit 0
fi


echo "dac_range_ALL=dac_range_??" >/etc/acq400/${SITE}/groups	
echo +++ initializing DACs for $MODEL mtype $MTYPE $*

EN=$(get.sys ${KNOBS}/dac_enable)
vset_sys ${KNOBS}/dac_enable 0
vset_sys ${KNOBS}/dacreset 1
vset_sys ${KNOBS}/dacreset 0
if [ "$MTYPE" = "$MOD_ID_AO422FMC" ]; then  # 32-bit writes
	vset_sys ${KNOBS}/dacspi 0x037f0000      # Clear Code, offset binary
        vset_sys ${KNOBS}/dacspi 0x06000040      # UP_RATE default
        vset_sys ${KNOBS}/dacspi 0x02004d00      # 5V default
        vset_sys ${KNOBS}/dacspi 0x04000020	 # Soft Reset
        vset_sys ${KNOBS}/dac_range_en 1         # works with new mod
else    # 24-bit writes
	vset_sys ${KNOBS}/dacspi 0x300000       # Clear Code
        vset_sys ${KNOBS}/dacspi 0x400002	# Soft Reset

	case $MODEL in
	ao428elf|cpsc2dac)
		vset_sys ${KNOBS}/dacspi 0x200002;; # +/- Ref Mult.
	*)
		vset_sys ${KNOBS}/dacspi 0x400002   # @@todo .. probably redundant
		if [ $SET_UNIPOLAR -eq 1 ]; then
		      vset_sys ${KNOBS}/dacspi 0x200012
		else
		      vset_sys ${KNOBS}/dacspi 0x200000
		fi;;
	esac
fi
vset_sys ${KNOBS}/dac_enable ${EN}

[ ! -e /etc/acq400/$SITE/wavegen ] && ln -s /usr/local/bin/wavegen /etc/acq400/$SITE

[ ! -e /etc/acq400/${SITE}/awg_seg ] && ln -s ${MODP}/awg_seg /etc/acq400/${SITE}/awg_seg

for gx in ${KNOBS}/G?; do
	[ -e $gx ] && set.sys $gx 32767
done

if [ "$MTYPE" != "$MOD_ID_AO422FMC" ]; then
        for rch in 1 2 3 4; do
	       [ -L ${EK}/dac_range_0${rch} ] || ln -s $KNOBS/dac_range_0${rch} ${EK}/dac_range_0${rch}
        done
fi

case $MODEL in
ao428elf)
	if [ "$(cat /etc/acq400/0/MODEL)" != "cpsc2" ]; then
		(cd /usr/local/lib/modules/
		/sbin/insmod adt7x10.ko
		/sbin/insmod adt7410.ko
		/sbin/insmod ao428.ko)
		rm -f /dev/hwmon/2/*	
		ln -s /sys/class/hwmon/hwmon4/device/temp1_input /dev/hwmon/2/temp
		ln -s /usr/local/CARE/dac20_autozero /etc/acq400/2/dac20_autozero
	fi
	;;
esac

cat - >>/etc/acq400/$SITE/groups <<EOF
dac_range_XX=dac_range_[0-9]*
AO_ALL=AO_[0-9]*
EOF

