#!/usr/bin/expect

set PID /var/run/acq400_stream_main.0.pid
set BUSY 0
log_user 0


proc test_busy {} {
	global PID BUSY

	try {
		exec kill -s 0 [exec cat $PID] 2>/dev/null
		set BUSY 1
	} trap CHILDSTATUS {results options} {
		set BUSY 0
	}
}

proc report {} {
	global BUSY
	puts "BUSY=$BUSY"
}


if {! [file exists $PID]} {
	set fd [open $PID w]
	puts $fd [expr [exec cat /proc/sys/kernel/pid_max] + 1]
	close $fd
}

test_busy

if { $::argc > 0 } {
	if { "[lindex $::argv 0]" == "nowait" } {
		report
		exit 0
	}
}
report

spawn inotifywait -e close_write $PID -m

while { 1 } {
	if { ! [file exists $PID] } {
		puts "ERROR: someone deleted $PID"
		exit 1
	}
	if { $BUSY == 0 } {
		expect -re "CLOSE_WRITE,CLOSE" {}
		# match or timeout, no problem
		test_busy
		if { $BUSY == 1 } { report }
	} else {
		after 100
		test_busy
		if { $BUSY == 0 } { report }
	}
}
