#!/bin/bash
# sourced from run0 and play0

# input $sites
# output SSB sample size bytes, NCHAN, D32 (master size)

NCHAN=0
ncc=0
D32=""
sitelist=""
sep=""

nspad=${nspad:-0}
d32c=$nspad
d16c=0
ssb=$(($nspad*4))

for site in $sites
do
	s_root=/etc/acq400/$site	
	if [ -e ${s_root}/data32 ]; then
		echo $ncc > ${s_root}/AGIX
		site_d32=$(get.site $site data32)
		active_chan=$(cat ${s_root}/active_chan)
		word_size=$(cat ${s_root}/word_size)
		ncc=$(($ncc+$active_chan))
		ssb=$(($ssb+$active_chan*$word_size))		
		if [ "x$D32" = "x" ]; then
			D32=$site_d32
		elif [ $D32 -ne $site_d32 ]; then
			echo "WARNING: mixed data size"
		fi
		sitelist="${sitelist}${sep}${site}"
		sep=","
		echo "site:$site ncc:$ncc ssb=$ssb AGIX=$(cat ${s_root}/AGIX)"
	else
		echo "ERROR: site $site does not exist"
	fi
done

NCHAN=$ncc
SSB=$ssb

echo "get_site_total_size D32:$D32 NCHAN:$NCHAN d32c:$d32c d16c:$d16c SSB:$SSB"


