#!/bin/sh
# configures site 0 aggregator.
# usage: run0 site1[,site2,..]  [spad-def]

S0KB=/dev/acq400.0.knobs
ETC0=/etc/acq400/0

spad2nchan() {
	mode=$1
	nwords=$2
	case $mode in
	0)
		echo 0;;
	1)
		echo $nwords;;
	2)
		echo 1;;
	esac
}

case x$1 in
x)
	get.sys $S0KB/aggregator
	exit 0;;
xdefault)
	shift
	source /etc/sites
	sitelist=$sites
	echo using default sitelist $sitelist;;
*)
	sitelist=$1
	if [ "x$2" != "x" ]; then
		set.site 0 spad=$2
		echo spad set $(get.site 0 spad)
	fi;;
esac

sites="$(echo $sitelist | tr , \ )"

echo sitelist: $sitelist
echo sites: $sites

rm -f $ETC0/run0_ready
acq400_teardown

spad3="$(tr , \  <$ETC0/spad)"
nspad=$((spad2nchan $spad3))
ssb=$(($nspad*4))

ncc=0
D32=""
sitelist=""
sep=""

for site in $sites
do
        s_root=/etc/acq400/$site
        if [ -e ${s_root}/data32 ]; then
                site_d32=$(get.site $site data32)
                active_chan=$(cat ${s_root}/active_chan)
                word_size=$(cat ${s_root}/word_size)

                echo $ncc > ${s_root}/AGIX
                ncc=$(($ncc+$active_chan))
                ssb=$(($ssb+$active_chan*$word_size))
                if [ "x$D32" = "x" ]; then
                        D32=$site_d32
                elif [ $D32 -ne $site_d32 ]; then
                        echo "WARNING: mixed data size"
                fi
                sitelist="${sitelist}${sep}${site}"
                sep=","
                echo "site:$site ncc:$ncc ssb=$ssb AGIX=$(cat ${s_root}/AGIX)"
        else
                echo "ERROR: site $site does not exist"
        fi
done

NCHAN=$ncc
SSB=$ssb


if [ ! -e $ETC0/NCHAN ] || [ $NCHAN -ne $(cat $ETC0/NCHAN) ]
then
	echo setting NCHAN:$NCHAN data32:$D32
	set.sys $ETC0/NCHAN $NCHAN
	set.sys $ETC0/data32 $D32
	/usr/local/bin/ai_monitor_all start	
fi

if [ -e $S0KB/has_axi_dma ] && [ $(cat $S0KB/has_axi_dma) -ge 1 ]; then
    threshold=2048
else
    threshold=16384
fi
set.sys $ETC0/sites 	${sitelist}
set.sys $ETC0/ssb 	$SSB
set.sys $ETC0/spadstart	$(($SSB-$nspad*4))

[ "x$NO_OPTIMISE_BUFFERLEN" = "xy" ] || set.sys $S0KB/optimise_bufferlen $SSB 

DECIM=$(get.sys $S0KB/decimate)
set.sys $S0KB/aggregator    0
set.sys $S0KB/data_engine_0 0
set.sys $S0KB/data_engine_0 aggregator=1 
set.sys $S0KB/aggregator    threshold=${threshold} sites=${sitelist%*,14}
set.sys $S0KB/decimate      $DECIM
set.sys $ETC0/run0_ready    1

echo $0 $* ssb=$SSB > /var/log/run0.log
